---
title: "Untitled"
author: "yasmin"
date: "2023-11-08"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(tidyverse)
```



```{r}

zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2022.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2022.csv")
data <- read_csv(csv_file)

row_number <- 375 
airdata <- data[row_number, , drop = FALSE]

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(row_number)
```


```{r} 

zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2021.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2021.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2020.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2020.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2019.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2019.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2018.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2018.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2017.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2017.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2016.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2016.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2015.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2015.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2014.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2014.csv")
data <- read_csv(csv_file)


mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2013.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2013.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2012.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2012.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2011.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2011.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2010.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2010.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2009.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2009.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2008.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2008.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2007.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2007.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2006.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2006.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2005.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2005.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2004.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2004.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2003.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2003.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2002.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2002.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2001.zip"
temp<- tempfile(fileext = ".zip")
download.file(zip_url, temp)
unzip(temp, exdir = tempdir())
list_of_files <- list.files(tempdir())
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2001.csv")
data <- read_csv(csv_file)

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery")
airdata <- rbind(airdata, mrow)

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)



zip_url <- "https://aqs.epa.gov/aqsweb/airdata/annual_aqi_by_county_2000.zip"
temp<- tempfile(fileext = ".zip");
download.file(zip_url, temp);
unzip(temp, exdir = tempdir());
list_of_files <- list.files(tempdir());
csv_file <- file.path(tempdir(), "annual_aqi_by_county_2000.csv");
data <- read_csv(csv_file);

mrow <- data %>% filter(State == "Maryland" & County == "Montgomery");
airdata <- rbind(airdata, mrow);

rm(zip_url)
rm(temp)
rm(list_of_files)
rm(csv_file)
rm(mrow)
rm(data)
```



```{r}
summary(airdata)
```

```{r}
graph <- airdata %>%
  ggplot(aes(x = Year, y = `Median AQI`)) +
  xlab("Years") +
  ylab("Air Quality Index")+
  ggtitle("Air Quality over the years") +
  scale_color_brewer(palette = "Set1")

graph + 
  geom_point() + geom_smooth()
```

